# Bottle-Agent 配置文件

# LLM配置
llm:
  provider: "volcengine"  # 支持: openai, volcengine
  model: "deepseek-r1-250120"  # OpenAI模型名称 或 火山引擎模型名称
  api_key: ""  # 在此填入您的API密钥，或设置环境变量OPENAI_API_KEY/ARK_API_KEY
  base_url: ""  # 可选：自定义API端点
  max_tokens: 2048
  temperature: 0.7
  timeout: 30
  
  # 火山引擎配置（当provider为volcengine时使用）
  volcengine:
    base_url: "https://ark.cn-beijing.volces.com/api/v3"
    api_key: "e61f4de8-e1f5-4996-ad2a-0592736be467"  # 火山引擎API密钥，或设置环境变量ARK_API_KEY
    model: "deepseek-r1-250120"  # 火山引擎模型ID
    timeout: 1800  # 深度思考模型建议设置较长超时时间




    

# 嵌入模型配置
embedding:
  provider: "openai"  # 支持: openai, huggingface
  model: "doubao-embedding-text-240715"  # 火山引擎嵌入模型
  # model: "sentence-transformers/all-MiniLM-L6-v2"  # HuggingFace模型示例
  api_key: "4298902b-e0b2-490e-b306-b0c31508338e"  # 火山引擎API密钥
  base_url: "https://ark.cn-beijing.volces.com/api/v3"  # 火山引擎API地址
  batch_size: 8
  max_length: 512

# 论文搜索配置
paper_search:
  # arXiv配置
  arxiv:
    base_url: "http://export.arxiv.org/api/query"
    max_results: 20
    sort_by: "relevance"  # relevance, lastUpdatedDate, submittedDate
    sort_order: "descending"  # ascending, descending
  
  # Semantic Scholar配置
  semantic_scholar:
    base_url: "https://api.semanticscholar.org/graph/v1"
    api_key: ""  # 可选：Semantic Scholar API密钥
    max_results: 20
    fields: "title,authors,abstract,year,url,citationCount,publicationDate,journal"
  
  # 标签推送配置
  notifications:
    check_interval_hours: 24  # 检查新论文的间隔（小时）
    max_notifications: 100    # 最大保存通知数量
    auto_cleanup_days: 30     # 自动清理旧通知的天数
    enable_auto_check: false  # 是否启用自动检查（需要定时任务支持）

# RAG系统配置
rag:
  # 文档处理
  document_processing:
    chunk_size: 1000  # 文档块大小
    chunk_overlap: 200  # 文档块重叠
    supported_formats: ["pdf", "txt", "md", "docx"]
  
  # 向量数据库
  vector_db:
    type: "faiss"  # 目前仅支持FAISS
    index_type: "IndexFlatIP"  # FAISS索引类型
    similarity_threshold: 0.7  # 相似度阈值
  
  # 检索配置
  retrieval:
    top_k: 5  # 默认检索的文档数量
    max_context_length: 4000  # 最大上下文长度

# 存储配置
storage:
  data_dir: "./data"  # 数据存储目录
  knowledge_bases_dir: "./data/knowledge_bases"  # 知识库存储目录
  cache_dir: "./data/cache"  # 缓存目录
  logs_dir: "./logs"  # 日志目录

# Web界面配置
web:
  host: "localhost"
  port: 8501
  title: "Bottle-Agent"
  description: "轻量学术搜索与RAG Agent"

# 日志配置
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_enabled: true
  console_enabled: true

# 性能配置
performance:
  max_concurrent_requests: 5
  request_timeout: 30
  cache_enabled: true
  cache_ttl: 3600  # 缓存过期时间（秒）